[package]
name = "hamletrs"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = "1.44", features = ["full"] }
rayon = "1.10"
criterion = { version = "0.5.1", features = ["html_reports"] }

[[bench]]
name = "tokio_benchmark"
harness = false
